name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download Web2App Compiler
        run: |
          git clone https://github.com compiler
          cd compiler
          sed -i 's|http://localhost:8080|https://perchance.org|g' app/src/main/assets/web2app.json

      - name: Build APK Final
        run: |
          cd compiler
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Product
        uses: actions/upload-artifact@v4
        with:
          name: Etincelle-APK
          path: compiler/app/build/outputs/apk/debug/app-debug.apk
